Repository campudus/tableaux-frontend, pull requests merged in 2019-06, with the labels that each got.

#104 added jenkinsfile which builds the frontend and saves everything as a…
  Jenkinsfile.legacy
Labels: review required

#110 Fix attachment history always showing "item was deleted"
  src/app/components/history/HistoryBody.jsx
  src/app/components/history/differ.js
  src/app/components/history/history-helpers.js
Labels: review required

#111 Fix service names showing `undefined`
  src/app/components/frontendService/FrontendServiceView.jsx
Labels: review required

#109 Recieve feedback via slack instead of sentry
  README.md
  dev-server.js
  src/app/components/dashboard/support/SupportWidget.jsx
  src/static/ServerConfigTool.js
  src/static/grud-frontend-server.js
Labels: review required

#114 Small style changes
  src/scss/header.scss
  src/scss/variables.scss
  src/static/img/GRUD-Logo.svg
Labels: visuals

#117 fix showDependency in ItemPopupMenu of EntityView
  src/app/components/entityView/ItemPopupMenu.jsx
Labels: bug, review required

#116 Centralise http requests
  src/app/components/cells/link/linkDisplayItemHelper.js
  src/app/components/dashboard/DashboardView.jsx
  src/app/components/dashboard/RequestStatusData.jsx
  src/app/components/helperComponents/SvgIcon.jsx
  src/app/components/helperComponents/needsAPIData.js
  src/app/components/media/folder/FileUpload.jsx
  src/app/components/media/overlay/FileChangeUpload.jsx
  src/app/components/media/overlay/MultilangFileDropzone.jsx
  src/app/helpers/apiHelper.js
  src/app/helpers/functools.js
  src/app/helpers/functools.test.js
Labels: code-enhancement
