Repository campudus/tableaux-frontend, pull requests merged in 2019-08, with the labels that each got.

#147 Fix rows-before-columns race condition
  src/app/redux/actionCreators.js
Labels: bug, prio:high, review required, testing welcome

#149 Fix translation view not reflecting EV changes
  src/app/components/overlay/EntityView/EntityViewBody.jsx
Labels: bug

#150 Prevent row concat helper crashing on array columns
  src/app/helpers/RowConcatHelper.js
Labels: bug

#152 Replace some leftover manual translations with helper
  src/app/components/cells/text/TextCell.jsx
  src/app/components/header/ColumnFilterPopup.jsx
  src/app/components/header/tableSettings/NameEditor.jsx
  src/app/components/header/tableSwitcher/TableSwitcher.jsx
  src/app/components/header/tableSwitcher/TableSwitcherPopup.jsx
  src/app/components/overlay/EntityView/columnFilter.js
Labels: bug, code-enhancement

#159 Fix initial visible Columns
  src/app/redux/actionCreators.js
Labels: review required

#156 [Deployment] Add some buildtime feature flags
  README.md
  src/app/FeatureFlags.js
  src/app/components/contextMenu/RowContextMenu.jsx
  src/app/components/header/tableSettings/TableSettings.jsx
  src/scss/filter.scss
  src/scss/tableSettings.scss
Labels: review required

#154 readd translation-confirmation and fix translation annotations
  src/app/components/cells/text/TextEditOverlay.jsx
  src/app/components/overlay/TranslationDialog.jsx
  src/app/redux/actions/annotationActions.js
  src/app/redux/actions/cellActions.js
Labels: review required

#162 Run lint
  src/app/components/cells/link/LinkOverlaySearchBar.jsx
  src/app/components/cells/numeric/NumericCell.jsx
  src/app/components/entityView/link/LinkView.jsx
  src/app/components/helperComponents/SvgIcon.jsx
  src/app/components/helperComponents/needsAPIData.js
  src/app/components/overlay/ColumnEditorOverlay.jsx
  src/app/frontendServiceRegistry/ServiceIcon.jsx
  src/app/helpers/functools.test.js
  src/stories/index.js
Labels: code-enhancement

#170 Cascade links
  src/app/components/cells/boolean/BooleanCell.js
  src/app/components/entityView/boolean/BooleanView.jsx
  src/app/redux/actions/cellActions.js
Labels: review required
